server:
  port: 8001
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: 172.17.9.209
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
